### ISSUE TITLE
SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by JToward** [akalongman/php-telegram-bot#116]
I am using GetUpdate method but I am still facing SSL error. What settings I need to set in GetUpdate method?

2016-03-09 13:38:22 exception 'Longman\TelegramBot\Exception\TelegramException' with message 'SSL certificate problem: self signed certificate in certificate chain' in C:\xampp\htdocs\t\src\Request.php:162
Stack trace:
#0 C:\xampp\htdocs\t\src\Request.php(239): Longman\TelegramBot\Request::executeCurl('getUpdates', Array)
#1 C:\xampp\htdocs\t\src\Request.php(397): Longman\TelegramBot\Request::send('getUpdates', Array)
#2 C:\xampp\htdocs\t\src\Telegram.php(359): Longman\TelegramBot\Request::getUpdates(Array)
#3 C:\xampp\htdocs\t\getUpdatesCLI.php(22): Longman\TelegramBot\Telegram->handleGetUpdates()
#4 {main}

**Comment by MBoretto** [comment]
Seem that you configuration can't start  the proper ssl connection.

**Comment by JToward** [comment]
Windows 8.1, PHP Version 5.6.8, curl 7.40.0.
I don't want to use webhook method thus it doesn't require SSL, right?

**Comment by noplanman** [comment]
Looks like a PHP/cURL issue, because it's sending the request using SSL to the Telegram API.
You are correct that you don't need any SSL to use the getUpdates() method, but your server needs an up to date CA bundle to communicate with the Telegram API server.

I found this guide for Windows online: https://wiki.cacert.org/HowTo/InstallCAcertRoots
As I don't use Windows I can't confirm that this works, but maybe you could give it a try and report back.

**Comment by MBoretto** [comment]
Feel free to reopen this if you need
