### ISSUE TITLE
The path to the downloaded file

### ISSUE THREAD

**Issue by yevstratov** [akalongman/php-telegram-bot#123]
Hey. I have a small question .
How can I get the path to the file after downloading ?

**Comment by MBoretto** [comment]
If you don't have overwritten the base_path is located here:
 https://github.com/akalongman/php-telegram-bot/blob/master/src/Telegram.php#L160

Then the last part of the path and the filename is the same provided by telegram File:
https://core.telegram.org/bots/api#file

Heres where is implemented:
 https://github.com/akalongman/php-telegram-bot/blob/master/src/Request.php#L237

I have answered at your question?

**Comment by yevstratov** [comment]
I do not know how to find out the name of the downloaded file , for later use conversation (((

**Comment by christianromeni** [comment]
It is not only one file... do you want to access the last file downloaded? Or do you want to pick from any file downloaded by that user?

**Comment by yevstratov** [comment]
I want to access last downloaded file.

**Comment by MBoretto** [comment]
Could you post the code?

**Comment by MBoretto** [comment]
should be there: https://github.com/akalongman/php-telegram-bot/blob/master/src/Request.php#L241

**Comment by noplanman** [comment]
In case this is still open:
```php
$doc = $message->getDocument();
$file_id = $doc->getFileId();
$file_location = $this->telegram->getDownloadPath() . '/';

$download = Request::getFile(['file_id' => $file_id]);
if ($download->isOk() && Request::downloadFile($download->getResult())) {
    $file_location .= $download->getResult()->getFilePath();
} else {
    $file_location = 'Failed to download.';
}

$this->conversation->notes['CSV_file'] = $file_id;
$text = 'File is located at: ' . $file_location;
```

@yevstratov Can we close here?

**Comment by xtrahost** [comment]
I was able to download files with your example. For photos this is not the best option because you will always get the smallest photo (thumbnail).

How could I change the code to get the biggest available quality or how can I chose between quality? As I know it has something to do with the file_id. I guess if the getFileId() function would return an array with all file_id's it could work...

$download = Request::getFile(['file_id' => $file_id[0]]); --> thumbnail
$download = Request::getFile(['file_id' => $file_id[1]]); --> low
$download = Request::getFile(['file_id' => $file_id[2]]); --> medium
etc.

`{"update_id":86454520, "message":{"message_id":814,"from":{"id":230182860,"first_name":"Max","last_name":"Muster"},"chat":{"id":230182860,"first_name":"Max","last_name":"Muster","type":"private"},"date":1465424082,"photo":[{"file_id":"AgADBAADq6cxG8xPuA3croVkhFI1CpEBQxkABAgyJ68ZZzc3W8gBAAEC","file_size":864,"file_path":"photo\/file_7.jpg","width":67,"height":90},{"file_id":"AgADBAADq6cxG8xPuA3croVkhFI1CpEBQxkABHp1OxmOe7t4XMgBAAEC","file_size":11809,"width":239,"height":320},{"file_id":"AgADBAADq6cxG8xPuA3croVkhFI1CpEBQxkABH28ffjuejWTXcgBAAEC","file_size":77936,"width":597,"height":800},{"file_id":"AgADBAADq6cxG8xPuA3croVkhFI1CpEBQxkABHjdEwukzU4eWsgBAAEC","file_size":183373,"width":956,"height":1280}]}}`

**Comment by noplanman** [comment]
Check my latest comment on the other issue [here](https://github.com/akalongman/php-telegram-bot/issues/221#issuecomment-224752729)
