### ISSUE TITLE
Bot state storage - your opinion?

### ISSUE THREAD

**Issue by pavlyuts** [akalongman/php-telegram-bot#179]
Hi all!

I need some way to store bot state and information in DB and working on fix for it. But I need you opinion.

The state storage wil be implemented as serialized object storage bound to chat (one chat - one state) with methods to save and retrieve objects. The key questions I have no decided yet:

1. Do we need user-bound storage instead of chat-bound? Or both?

2. How big the storage should be? There some performance and scalability issue arise: we can use varchar(), but it means we need to decide on max amount of stored data, and the limit will be toolkit-wide. More space - bigger record size, while the size requiremens very different on different projects. As well we can use TEXT type with almost no limin, but another performance issue here: TEXT type does not cached by DB and always reads from disk directly. I am not sure which way is the best.

3. We can put VARCHAR or TEXT field to 'chat' table or use separate table bound to chat id. 

Any ideas? Opinions? It's you project, finally ))))

**Comment by MBoretto** [comment]
I don't understand exactly what is your goal.
Bind this `state` table to the chat or user or both depends on the information you would like to store.
Furthermore if you know which information you would like to store why don't you create a column for each field instead of serializing everything? Or maybe you can go for an hybrid solution see  `conversation` table.
Let me know

**Comment by pavlyuts** [comment]
Ok, let me explain. By default the bot is stateless by you toolkit. Conversation is the way to make it a bit state-aware within one command. Sure, everyone can create extra data strucrure and handle any information. But for simple case where the bot state data is relatively small and simple I think to use very simple, low-code save-retrieve way, reusing PDO from the toolkit. 

For example, add two method to the "command" class, saveContext ($context ) and getContext (). The command always bound to chat/user therefore it's plain and simple.

If I need some context data to survive I do saveContext ($data) and don't care. If I need to use context on the next update/command/e.t.c. I just start with $data = getContext.

Something about this. I can do that thing out of you toolkit, but I prefer to contribute it to the toolkit because think it's usefull.

**Comment by MBoretto** [comment]
Before implementing new general purpose things  we have to find a specific function to introduce in the bot. For example Conversation -> /survery and /SendToChannel Commands.

Anyway what you propose can be useful, I'm afraid to spend time to introduce a feature like this now because i think will be better if first we complete what we have and after we will add more features. (I wait a lot of time before introduce conversation https://github.com/akalongman/php-telegram-bot/issues/7)

For example:
- Introducing markdown in all the commands
- /stats commad https://github.com/akalongman/php-telegram-bot/issues/64
- Conversation in all admins commands
... and many others

let me know
