### ISSUE TITLE
How to disable and translate default commands?

### ISSUE THREAD

**Issue by Sogl** [akalongman/php-telegram-bot#183]
Hello!

I use `getUpdate` method. In Telegram client I see much commands after `/start` that I don't really need, like `/weather` or `/date`. How to correctly disable them?

Also some commands I want to use, but they not translated to my language. Just copy and rewrite them in my `commands` folder or there is a better option?

**Comment by jacklul** [comment]
You can safely remove the files or create dummy commands in extra commands folder, example:

**mycommands/DateCommand.php:**
```<?php
namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;

class DateCommand extends SystemCommand
{
}
```
**Why changing it to SystemCommand?** _SystemCommands does not show in /help listing_

If you want to translate specific command you have no other option but to copy it to extra commands folder and edit.

Alternatively, you can store your bot's code in local repository, remove the command files and then commit it, updating the bot in the future will be less painful this way.

_P.S. Do not delete commands from SystemCommands, especially the ones handling inline/callback queries, otherwise they will be handled by GenericCommand in a wrong way which will throw some errors out!_

**Comment by Sogl** [comment]
>Why changing it to SystemCommand? SystemCommands does not show in /help listing

Disabling also works with `protected $enabled = false;` option. Maybe it's the better way?

**Comment by jacklul** [comment]
I can't remember why I did it like this, maybe there was an issues or something.
But yeah, you can created dummy command with ```protected $enabled = false;``` instead.
