### ISSUE TITLE
my commands are not discovered

### ISSUE THREAD

**Issue by novia713** [akalongman/php-telegram-bot#270]
i was using an old version of php-telegram-bot
today i decided to clone the project, i edited my getUpdatesCli.php as needed 
run the structure.sql ... so far it works

now i moved to ./Commands my old custom commands (they were working with the old version)
this is my config for them
```
$COMMANDS_FOLDER = __DIR__.'/Commands/';
$telegram->addCommandsPath($COMMANDS_FOLDER);
```
this is an example of one of my commands
http://paste.debian.net/789715/

**Comment by noplanman** [comment]
Looks like you've come from a very old version!

Check out the new example commands, to see how the new command system works.

There are 3 different command types: System, Admin and User (with their respective classes to extend on: SystemCommand, AdminCommand and UserCommand).
So instead of extending the general Command class, you would need to extend UserCommand (or AdminCommand if it's a command that should only be available to admins)

**Comment by novia713** [comment]
uh, yes, it works now ^^
somebody update the wiki, please
i can't find that info on it

thanks @noplanman

**Comment by noplanman** [comment]
Wiki has been updated, thanks for pointing that out!
