### ISSUE TITLE
Code style, content

### ISSUE THREAD

**Issue by boukeversteegh** [akalongman/php-telegram-bot#57]
Dear developers,

I'm glad a fairly popular php client such as this one exists for the telegram bot API. However, as I am walking through the source code, trying to figure out how it works internally, I get confused.

- I see commented lines of code (dead code). I wonder why it is there, whether it is a stub to be implemented, or old code that is no longer relevant, or accidentally left over debugging statements.  
https://github.com/akalongman/php-telegram-bot/blob/master/src/Telegram.php#L597  
https://github.com/akalongman/php-telegram-bot/blob/master/src/Request.php#L142
- Other code that does not seem to be used, obvious from the typo and no single call is made to it:  
https://github.com/akalongman/php-telegram-bot/blob/master/src/Request.php#L85  
https://github.com/akalongman/php-telegram-bot/blob/5d3a1209afdfab9d59e9ac6678c4e6e037dfd1a3/src/Telegram.php#L323
- Verbosity levels seem configurable, yet the Telegram class just randomly ``print_r``'s and ``echo``'s without looking at verbosity levels. Actually I don't think a library should print anything to stdout at all, unless its purpose is to print things, but that aside.  
https://github.com/akalongman/php-telegram-bot/blob/master/src/Telegram.php#L370
- I see in some places an api call returns the result, in others it prints it, in others it writes it to a database.  
https://github.com/akalongman/php-telegram-bot/blob/master/src/Telegram.php#L347  

At this point I am thinking whether I should start contributing on this project or not. I would like to, but such things above make it a bit of a challenge. I would recommend to clean up the code a bit to make it easier for external developers to start contributing. This is just my opinion, but I think it would help the project.

**Comment by akalongman** [comment]
@boukeversteegh Thank you for your opinion. We will be very glad if you will help with cleaning and refactoring this code.

**Comment by MBoretto** [comment]
Hello,
thanks for the feedback. I admit that I spend my efforts in developing a full support to the API instead of clean the code. I agree with all the things you pointed out and seem to me a good goal for the future releases.
Fist of all, I will remove all the comment than I leave.
-The library shouldn't print anything and this have to be fixed.
- For what concern the "non used code". Those functions has been used to develop/testing the library. Defining a PHPUNIT_TESTSUITE var you can inject in the system a json string. I think that this code could be moved in tests. https://github.com/akalongman/php-telegram-bot/blob/master/src/Request.php#L241
 
If you have any questions  or you need further clarification don't hesitate to ask!

**Comment by alpastar** [comment]
i appreciate your effort 
but however, i have  one question , trying to figure out  why 

$a_result= json_decode($result, true)                               //  parse as array, not object
$o_message = new Message($a_result,$c_bot_name)    // make a  messageobject  from array 

why decode as a array, is there  any problem when make a  object from object?
(example)
$o_result= json_decode($result)                                       //  parse as  object
$o_message = new Message($o_result,$c_bot_name)

**Comment by noplanman** [comment]
Found myself in the same boat as @boukeversteegh when I found this project.

I'm a huge fan of pretty and clean code and love doing the cleaning / optimising.

Are you still open to having the code cleaned up? I've put some work into prettifying `Telegram.php` as a starting point, because it seemed the most worked on file. If you like, I can make a PR so you can see the changes I've done and give me feedback on what you do and don't like. This way, I can adapt and start cleaning up other files, one by one.

As with all open source projects that have multiple people and different experience levels working on the code, I understand that nobody has the "perfect" style that everybody likes. For this reason I'd like to start small and possibly find a style guide that works for you guys and help do the grunt work :blush: 

The great side effect of doing this, is that I learn how the internals of this project works, which is the whole reason why I landed here in the first place :wink:

**Comment by MBoretto** [comment]
Hello, @noplanman ! What a nice news! I'm happy to hear that you would contribute to the project! 
In the latest month I worked alone, and I think that another point of view can help the library a lot. So feel free to change clean and improve! 
We can create a new branch to review and discuss your PR! 😃😃

**Comment by MBoretto** [comment]
Code cleanup was performed in the command part of the library. 
In the future we should start the  entities part.
Thanks to @noplanman for the hard work!  :balloon:
