### ISSUE TITLE
The path used for writing to `TelegramException.log` is a security risk

### ISSUE THREAD

**Issue by dstotijn** [akalongman/php-telegram-bot#96]
The `TelegramException` class writes a log file `TelegramException.log` in the current path of the executing PHP script, because `file_put_contents` is called with just a filename. This can be a security risk when a public facing web server is in place, where the log file could be in the document root and can be accessed.

**Comment by noplanman** [comment]
You're absolutely right, thanks for pointing this out!

An easy fix would be to restrict access to the file using .htaccess or within the nginx configuration.

Other option would be to offer the option to choose the destination of the `TelegramException.log` file. This would require the user to set the destination and actually make sure that it can't be accessed.

#88 Might need to be implemented after all.

Also, we'll need to add a simple .htaccess / nginx config snippet to the readme, so that users can protect themselves.

**Comment by ivanbaldo** [comment]
Maybe this could be closed now?
Commit https://github.com/akalongman/php-telegram-bot/commit/b1184d862d17fb8e300d57944658a9608742f904 deals with this.

**Comment by MBoretto** [comment]
yes thanks!
